# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-12 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citizen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
                ('vote_yes', models.IntegerField()),
                ('vote_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('acts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Acts')),
                ('topics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('party', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=30)),
                ('profession', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('speech', models.TextField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Acts')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Member')),
            ],
        ),
        migrations.AddField(
            model_name='acts',
            name='topics',
            field=models.ManyToManyField(through='parliament.Dates', to='citizen.Topic'),
        ),
    ]
