# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-12 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citizen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('act_type', models.CharField(max_length=20)),
                ('status', models.IntegerField(blank=True)),
                ('vote_yes', models.IntegerField(blank=True)),
                ('vote_no', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Act')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('party', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=30)),
                ('profession', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MemberAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Act')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speech_type', models.CharField(max_length=30)),
                ('speech', models.TextField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Act')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Member')),
            ],
        ),
        migrations.AddField(
            model_name='act',
            name='topic',
            field=models.ManyToManyField(through='parliament.Date', to='citizen.Topic'),
        ),
    ]
