# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0002_auto_20161113_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberact',
            name='vote',
            field=models.NullBooleanField(),
        ),
    ]
