# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0003_memberact_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='act',
            name='act_type',
        ),
        migrations.AlterField(
            model_name='act',
            name='name',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='act',
            name='vote_no',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='act',
            name='vote_yes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
