# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0004_auto_20161113_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MemberBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Board')),
            ],
        ),
        migrations.RenameField(
            model_name='member',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='board_type',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
        migrations.AddField(
            model_name='memberboard',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Member'),
        ),
        migrations.AddField(
            model_name='board',
            name='member',
            field=models.ManyToManyField(to='parliament.Member'),
        ),
    ]
