# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0002_auto_20161112_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='votes_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='votes_up',
            field=models.IntegerField(default=0),
        ),
    ]
