# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0005_auto_20161113_1313'),
        ('citizen', '0004_topic_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemsolved',
            name='user',
        ),
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problemsolved',
            name='description',
            field=models.TextField(default='', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problemsolved',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parliament.Member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problemsolved',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='citizen.Problem'),
            preserve_default=False,
        ),
    ]
