# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0005_auto_20161113_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='image',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.TextField(default=''),
        ),
    ]
